@URL = http://localhost:3000/api

###
GET {{URL}}/authors

###
POST {{URL}}/authors
Content-Type: application/json

{
    "nombre": "Mario Ruiz",
    "email": "mario@example.com",
    "imagen": "https://picsum.photos/200"
}


###
GET {{URL}}/authors/3/posts/count

###
POST {{URL}}/authors
Content-Type: application/json

{
    "nombre": ""
}

###

GET {{URL}}/posts

###
GET {{URL}}/posts/2

###
POST {{URL}}/posts
Content-Type: application/json

{
    "titulo": "Sin datos"
}